#!/bin/bash
# 手动触发Make工作流
echo "📝 请手动在Make.com中触发工作流"
echo ""
echo "步骤："
echo "1. 登录 https://www.make.com"
echo "2. 打开你的Biomat Video工作流"
echo "3. 点击右上角的 'Run once' 按钮"
echo "4. 等待工作流执行完成（可能需要5-10分钟）"
echo "5. 查看每个节点的执行结果"
echo ""
echo "特别注意："
echo "- 节点1（定时器）应该显示当前时间"
echo "- 节点2（HTTP请求）应该显示API响应"
echo "- 节点3（下载）应该显示下载的视频URL"
echo "- 节点4（YouTube上传）应该显示上传成功"
echo ""
echo "📊 期望结果："
echo "- 节点2应该返回一个真实的视频URL（不是big_buck_bunny）"
echo "- 视频URL应该包含 'video_generate_cgt-' 字符串"
echo ""
echo "📝 如果仍然是测试视频，请："
echo "1. 点击节点2查看API的完整响应"
echo "2. 查看响应中的 'execution_time' 确认是新部署"
echo "3. 将响应内容发送给我进行分析"
